// Generated by nuxt-seo-utils.assets

declare module '#app' {
  import { HeadEntry, HeadTag } from '@unhead/schema'

  interface RuntimeNuxtHooks {
    'head:tags': (tag: HeadTag[]) => Promise<void> | void
    'head:entries': (entries: HeadEntry[]) => Promise<void> | void
  }
}
declare module '@unhead/schema' {

  type PublicFiles = '/_robots.txt' | '/favicon.ico' | '/images/EGH.webp' | '/images/IDLOGO.webp' | '/images/OG.webp' | '/images/Regional.webp' | '/images/Yates.webp' | '/images/computer.webp' | '/images/corelogic.webp' | '/images/fat8.webp' | '/images/g2.webp' | '/images/idrew.webp' | '/images/idrewfilm.webp' | '/images/luscos.webp' | '/images/madg.webp' | '/images/madgcover.webp' | '/images/mdcc.webp' | '/images/me_1.webp' | '/images/me_3.webp' | '/images/olemiss.webp' | '/images/taylortrolley.webp' | '/images/thompson.webp' | '/images/tools.webp' | (string & Record<never, never>)
  type JsFiles = (string & Record<never, never>)

  interface SchemaAugmentations {
    link: import('@unhead/schema').UserTagConfigWithoutInnerContent & {
      href: PublicFiles
    }
    script: import('@unhead/schema').TagUserProperties & {
      src: JsFiles
    }
  }
}
export {}
